proper name of image in ci check
Signed-off-by: Dzmitry Lahoda <dzmitry@lahoda.pro>

diff --git a/.github/templates/docker-publish/action.yml b/.github/templates/docker-publish/action.yml
--- a/.github/templates/docker-publish/action.yml
+++ b/.github/templates/docker-publish/action.yml
@@ -54,19 +54,20 @@ runs:
 
         SHA256=$(sha256sum ./result | cut --delimiter " " --fields 1)
 
-        docker run $SHA256
-        RESULT=$? 
-        if [ $RESULT -eq 127 ]
-        then 
-          printf "Failed test run docker container %s" $RESULT
-        fi
-
         COMMIT_SHA=$(git rev-parse HEAD)
         CONTAINER_NAME=${{ inputs.name }}
         TEMP_CONTAINER_NAME=${{ inputs.artifact }}
 
         docker tag "${TEMP_CONTAINER_NAME}" "${{ env.DOCKER_REGISTRY_NAME }}/${CONTAINER_NAME}:${SHA256}"
         docker tag "${TEMP_CONTAINER_NAME}" "${{ env.DOCKER_REGISTRY_NAME }}/${CONTAINER_NAME}:${COMMIT_SHA}"
+
+        docker run "${TEMP_CONTAINER_NAME}"
+        RESULT=$? 
+        if [ $RESULT -eq 127 ]
+        then 
+          printf "Failed test run docker container %s" $RESULT
+        fi
+
         if [ $(git symbolic-ref HEAD) = "refs/heads/main" ]; then
           docker tag "${TEMP_CONTAINER_NAME}" "${{ env.DOCKER_REGISTRY_NAME }}/${CONTAINER_NAME}:latest"
         fi;
