more deps missing

diff --git a/.github/workflows/build-test-deploy.yml b/.github/workflows/build-test-deploy.yml
--- a/.github/workflows/build-test-deploy.yml
+++ b/.github/workflows/build-test-deploy.yml
@@ -1112,9 +1112,19 @@ jobs:
 
           if [ "$DEVNET_MAIN" != "$DEVNET_PR" ] || [ "$TESTS_MAIN" != "$TESTS_PR" ]; then
             ( nix run .#devnet-dali 2>&1 & ) | tee devnet-dali.log &
-            until test -f devnet-dali.log; do sleep 1 && echo "waiting network start"; done;
-
-            ( tail --follow --lines=0  devnet-dali.log & ) | grep --max-count=1 "Network launched 🚀🚀"
+            until test -f devnet-dali.log; do
+              sleep 1 && echo "waiting network start";
+            done;
+            TIMEOUT=240
+            COMMAND="( tail --follow --lines=0  devnet-dali.log & ) | grep --max-count=1 \"Network launched 🚀🚀\""
+            set +o errexit
+            timeout $TIMEOUT bash -c "$COMMAND"
+            START_RESULT="$?"
+            set -o errexit
+            if [[ $START_RESULT -ne 0 ]] ; then 
+              printf "failed to start devnet within %s with exit code %s" "$TIMEOUT" "$START_RESULT"
+              exit $START_RESULT
+            fi
             echo "PATH=$(pwd):$PATH" >> $GITHUB_ENV
             cd code/integration-tests/runtime-tests || exit
             npm install -q
